CHARACTERS = [

    ("이누야샤", "Inuyasha", "inuyasha.png"),
    ("셋쇼마루", "Sesshomaru", "sesshomaru.png"),
    ("가영", "Kagome Higurashi", "kagome.png"),
    ("키쿄우", "Kikyo", "kikyo.png"),
    ("산고", "Sango", "sango.png"),
    ("미로쿠", "Miroku", "miroku.png"),
    ("싯포", "Shippo", "shippo.png"),
    ("나라쿠", "Naraku", "naraku.png"),
    ("코우가", "Koga", "koga.png"),
    ("카구라", "Kagura", "kagura.png"),

    ("칸나", "Kanna", "kanna.png"),
    ("링", "Rin", "rin.png"),
    ("쟈켄", "Jaken", "jaken.png"),
    ("코하쿠", "Kohaku", "kohaku.png"),
    ("키라라", "Kirara", "kirara.png"),

    ("카에데", "Kaede", "kaede.png"),
    ("묘가", "Myoga", "myoga.png"),
    ("토토사이", "Totosai", "totosai.png"),
    ("아야메", "Ayame", "ayame.png"),
    ("츠바키", "Tsubaki", "tsubaki.png"),

    ("유라", "Yura", "yura.png"),
    ("이자요이", "Izayoi", "izayoi.png"),
    ("투아왕", "Toga", "toga.png"),
    ("셋쇼마루의 어머니", "Sesshomaru's Mother", "sesshomaru_mother.png"),
    ("아운", "Ah-Un", "ahun.png"),

    ("하쿠도시", "Hakudoshi", "hakudoshi.png"),
    ("뱌쿠야", "Byakuya", "byakuya.png"),
    ("아기", "The Infant", "infant.png"),
    ("무소", "Muso", "muso.png"),
    ("고신키", "Goshinki", "goshinki.png"),

    ("주로마루", "Juromaru", "juromaru.png"),
    ("카게로마루", "Kageromaru", "kageromaru.png"),
    ("모우료마루", "Moryomaru", "moryomaru.png"),
    ("아카고", "Akago", "akago.png"),
    ("반코츠", "Bankotsu", "bankotsu.png"),

        ("쟈코츠", "Jakotsu", "jakotsu.png"),
    ("렌코츠", "Renkotsu", "renkotsu.png"),
    ("스이코츠", "Suikotsu", "suikotsu.png"),
    ("긴코츠", "Ginkotsu", "ginkotsu.png"),
    ("무코츠", "Mukotsu", "mukotsu.png"),
    ("쿄코츠", "Kyokotsu", "kyokotsu.png"),

    ("류코츠세이", "Ryukotsusei", "ryukotsusei.png"),
    ("가텐마루", "Gatenmaru", "gatenmaru.png"),
    ("효네코", "Hyoneko", "hyoneko.png"),
    ("토우란", "Toran", "toran.png"),
    ("슈란", "Shuran", "shuran.png"),
    ("케슌", "Karan", "karan.png"),
    ("춘란", "Shunran", "shunran.png"),

    ("시신키", "Shishinki", "shishinki.png"),
    ("호센키", "Hosenki", "hosenki.png"),
    ("호센키 2세", "Hosenki II", "hosenki2.png"),

    ("소타", "Sota Higurashi", "sota.png"),
    ("가영 엄마", "Mrs. Higurashi", "kagome_mother.png"),
    ("가영 할아버지", "Kagome's Grandfather", "kagome_grandfather.png"),
    ("호죠", "Hojo", "hojo.png"),
    ("에리", "Eri", "eri.png"),
    ("유카", "Yuka", "yuka.png"),
    ("아유미", "Ayumi", "ayumi.png"),

    ("메노마루", "Menomaru", "menomaru.png"),
    ("카구야", "Princess Kaguya", "kaguya.png"),
    ("호시요미", "Hoshiyomi", "hoshiyomi.png"),
    ("사라 공주", "Princess Sara", "princess_sara.png"),
    ("세츠나의 타케마루", "Takemaru", "takemaru.png"),
    ("루리", "Ruri", "ruri.png"),
    ("하리", "Hari", "hari.png"),

    ("나즈나", "Nazuna", "nazuna.png"),
    ("하치에몽", "Hachiemon", "hachiemon.png"),
    ("아비", "Abi", "abi.png"),
    ("긴타", "Ginta", "ginta.png"),
    ("하쿠카쿠", "Hakkaku", "hakkaku.png"),
]